import { Inter } from "next/font/google";
import "./globals.css"
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "../db/session.js";
import { getServerSession } from "next-auth";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}> <SessionProvider session={session}>{children}      </SessionProvider></body>
    </html>
  );
}
